---
title: "14 April 2023"
author: "Ian McDonald"
date: "2023-04-14"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## In early March, Sight and Sound published detail of the individual ballots used to compile the 2022 Greatest Films survey. I scraped the publicly avaiable data and compiled data tables that can be used to compare clusters of voters based on their preferences.

After Sight and Sound increased the respondent pool, and with the passage of ten years, some changes in the ranking results emerged compared to the 2012 survey. Famously, Chantal Akerman's \*Jeanne Dielman, 23, quai du commerce, 1080 Bruxelles\* released in 1975, vaulted from 32nd to 1st in the 2022 critics poll. \*Jeanne Dielman\* replaced \*Vertigo\* as the most widely chosen film, which in turn had replaced the perennial #1 \*Citizen Kane\* (both 2 and 3 in 2022 respectively).

We're asking if a signficiant number of voters participated in this change, other changes in the rankings, and their geographic distribution. In the coming weeks, I'll pursue a number of other analyses looking for clusters of support and the degree to which voters choose similar kinds of films, and the regions that might change the results.

Voters pick ten films without ranking them. The overall rankings are simply based on the frequency that films appear on the ballots. The balloting process is simple and freely permits idiosyncratic choices that aren't shared by many critics. Even the top films are chosen by a relatively small number of voters.

2022 was notable for the near doubling of the respondent pool. For the 2022 critics vote, \*Jeanne Dielman\* was chosen by 215 of 1615 critics, or 13.3%. In my reading, that percentage seems small given the visibility generated by Jeanne Dielman's success in the poll. The 13.3 percentage is measurably smaller than 2012's #1 film, Vertigo, achieved: 191 of 846 voters, or 22.6%.

I think this represents an iimportant trend from 2012: voters were more willing to choose underrecognized films that weren't top of the 2012 lists, or any other list for that matter. Can we find taste patterns based on movie choices that will predict other kinds of selections? Are Citizen Kane voters less likely to choose Jeanne Dielman, for instance? Can we identify blocs of voters that cluster around similar films?

This summary reports the top overall choices and the number of votes for the top 20 films, and then shows the top 20 for several regions of the voting critics.

## Top 20 Overall Critics Vote Count

''' {r}

library(tidyverse)

all_critics \<- read_csv("all_critics.csv")



library(knitr)
kable(head(cars))

print(2+2)
'''
